volumes:
  n8n_data: {}
  # postgres_data and redis_data removed - using external services

x-n8n-service: &n8n_service
  image: n8nio/n8n:latest
  restart: always
  env_file: .env
  volumes:
    - n8n_data:/home/node/.n8n
  deploy:
    resources:
      limits:
        memory: 1G
        cpus: '0.5'
      reservations:
        memory: 512M
        cpus: '0.25'

services:
  n8n:
    <<: *n8n_service
    ports:
      - "5678:5678"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# n8n-worker:
  #   <<: *n8n_service
  #   command: worker
  #   environment:
  #     - N8N_WORKER_TYPE=worker
  #   depends_on:
  #     n8n:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD", "ps", "aux", "|", "grep", "-v", "grep", "|", "grep", "n8n"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 60s

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/load-balancer/n8n-load-balancer.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      n8n:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s