volumes:
  n8n_data: {}
  # postgres_data and redis_data removed - using external services

x-n8n-service: &n8n_service
  image: n8nio/n8n:latest
  restart: always
  env_file: .env
  volumes:
    - n8n_data:/home/node/.n8n
  # Using external GCP CloudSQL and Redis Cloud - no local dependencies needed

services:
  # postgres and redis services removed - using external GCP CloudSQL and Redis Cloud

  n8n:
    <<: *n8n_service
    ports:
      - "5678:5678"

  n8n-worker:
    <<: *n8n_service
    command: worker
    environment:
      - N8N_WORKER_TYPE=worker
    depends_on:
      - n8n

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/load-balancer/n8n-load-balancer.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - n8n
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "-o", "/dev/null", "http://127.0.0.1/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s