# ────────────────────────────────
# Prometheus Configuration for n8n Scaling Monitoring
# ────────────────────────────────

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'n8n-production'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # n8n main instance monitoring
  - job_name: 'n8n-main'
    static_configs:
      - targets: ['n8n-main:5678']
    scrape_interval: 15s
    metrics_path: /metrics
    params:
      format: ['prometheus']
    basic_auth:
      username: 'admin'
      password: 'SuperSecureUIpass!'

  # n8n worker instances monitoring
  - job_name: 'n8n-workers'
    static_configs:
      - targets: ['n8n-worker:5679']
    scrape_interval: 15s
    metrics_path: /health
    params:
      format: ['prometheus']

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    metrics_path: /metrics

  # PostgreSQL monitoring (if pg_exporter is added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics

  # Docker container monitoring
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  # Nginx monitoring
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

# Remote write configuration (for external monitoring)
# remote_write:
#   - url: "https://your-remote-prometheus-endpoint/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"
